<?php get_template_part('templates/html', 'header'); ?>
<?php get_template_part('templates/frontpage', 'slider'); ?>      
<?php get_template_part('templates/frontpage', 'banner'); ?>   
<?php get_template_part('templates/frontpage', 'atividades'); ?>
<?php get_template_part('templates/frontpage', 'video'); ?>
<?php get_template_part('templates/frontpage', 'doacao'); ?>
<?php get_template_part('templates/frontpage', 'comunidade'); ?>
<?php get_template_part('templates/frontpage', 'nossosprojetos'); ?>
<?php get_template_part('templates/frontpage', 'contato'); ?>
<?php get_template_part('templates/html', 'footer'); ?>